In [1]:
import pandas as pd
from string import Template
from pathlib import Path
import json

DATA_FILE_GEMMA = Path("data/gemma-multilingual-zero-prompts.csv")
DATA_FILE_QWEN = Path("data/qwen-multilingual-zero-prompts.csv")

In [2]:
qwen_df = pd.read_csv(DATA_FILE_QWEN)
gemma_df = pd.read_csv(DATA_FILE_GEMMA)

In [3]:
marathi_df = gemma_df[gemma_df['language']=="Marathi"].copy().reset_index(drop=True)
sinhala_df = gemma_df[gemma_df['language']=="Sinhala"].copy().reset_index(drop=True)
tamil_df = gemma_df[gemma_df['language']=="Tamil"].copy().reset_index(drop=True)

In [4]:
albanian_df = qwen_df[qwen_df['language']=="Albanian"].copy().reset_index(drop=True)
odia_df = qwen_df[qwen_df['language']=="Odia"].copy().reset_index(drop=True)
hindi_df = qwen_df[qwen_df['language']=="Hindi"].copy().reset_index(drop=True)
punjabi_df = qwen_df[qwen_df['language']=="Punjabi"].copy().reset_index(drop=True)

In [37]:
albanian_df

,UUID,country,curriculum,addressing,grade,topic,topic_list,zeroshot_prompt,language,multilingual_prompt
0,c63d5de6-0ef9-484a-b31d-19b5254b735d,Albania,Albanian National,Albanian,3,1. Number and Operations : Calculate the sum o...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
1,25ec454c-a879-4ce1-9716-bedd0a4b55f3,Albania,Albanian National,Albanian,3,2. Number and Operations : Calculate the diff...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
2,c80031d5-0f9a-405f-8086-a46e01f545b3,Albania,Albanian National,Albanian,3,3. Number and Operations : Multiply a 1-digit ...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
3,3551bbd5-6360-4daa-ac8d-c9d3726f85d8,Albania,Albanian National,Albanian,3,4. Number and Operations : Divide a 1-digit nu...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
4,89cc30d5-bf9d-44cb-84ab-8bab34ee017d,Albania,Albanian National,Albanian,3,5. Number and Operations : Calculate a given ...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
5,0308671e-a310-4df0-979c-3bc7a312516a,Albania,Albanian National,Albanian,3,6. Operations : Translate word problems involv...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
6,e525b2b2-3328-4f96-a75f-017217c6bb43,Albania,Albanian National,Albanian,3,7. Operations : Solve practical word problems ...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
7,d1085428-d3e4-49b1-b2f4-cabe2eaadb69,Albania,Albanian National,Albanian,3,8. Measurement : Measure the length of an obje...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
8,3d05bfd3-778c-4ca4-a816-c5caf86658f7,Albania,Albanian National,Albanian,3,9. Measurement : Measure the mass of an object...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
9,226a4aa9-8b0c-4ad5-876c-2549a6ed4a80,Albania,Albanian National,Albanian,3,"10. Data handling : Solve one-step ""how many m...",1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
10,ef740079-d428-4c1e-92b7-95b9a369840f,Albania,Albanian National,Albanian,4,1. Number and Operations : Calculate the sum o...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
11,1db53124-22bb-4f6d-9ac8-39286dcdc990,Albania,Albanian National,Albanian,4,2. Number and Operations : Calculate the diff...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
12,5ee2540a-3693-477a-a0a2-e26a884b9b53,Albania,Albanian National,Albanian,4,3. Number and Operations : Multiply a whole nu...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
13,98b54745-4448-4451-8501-9f76d8c3322d,Albania,Albanian National,Albanian,4,4. Number and Operations : Divide whole number...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
14,4311be70-5fb3-4b72-8f80-f4d3ea5d55a3,Albania,Albanian National,Albanian,4,5. Number Systems : Perform addition using dec...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
15,ce16dc70-b357-4f0b-8317-9feb26bfd4c4,Albania,Albanian National,Albanian,4,6. Number Systems : Perform subtract using dec...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
16,2d176d9b-d9d4-42da-9bbc-12400933be6f,Albania,Albanian National,Albanian,4,7. Number Systems : Locate and plot positive a...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
17,000f181e-3b39-439c-a9a8-994313a60c75,Albania,Albanian National,Albanian,4,8. Measurement : Solve word problems that inv...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
18,d2d1313a-98a7-4824-8979-452f0d2ee0e5,Albania,Albanian National,Albanian,4,9. Measurement : Tell time to the exact minute...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
19,1e86b171-eb0a-4485-abed-6cb3a6f70708,Albania,Albanian National,Albanian,4,10. Measurement : Solve measurement problems t...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
20,bc514ad7-497b-4c30-b9ab-a02154762e49,Albania,Albanian National,Albanian,4,11. Data handling : Display a set of measureme...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
21,84f47e2a-1023-4e5c-8301-3e305ff46290,Albania,Albanian National,Albanian,4,12. Data handling : Answer questions about th...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
22,4aad8cf7-3696-40e1-8728-1c0146a5e78d,Albania,Albanian National,Albanian,5,1. Geometry : Learn that an angle is measured ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
23,9a91392a-3849-4d35-97de-ed50ccb8785d,Albania,Albanian National,Albanian,5,2. Geometry : Sort triangles into groups based...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
24,f6cf06f0-50f4-44da-b264-33621c71fa4b,Albania,Albanian National,Albanian,5,3. Number and Operations : Add and subtract fr...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
25,f7f09787-20aa-4d2b-be7f-30e5f7999c58,Albania,Albanian National,Albanian,5,4. Number and Operations : Compare any two who...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
26,b5ad2eff-6704-4c25-b92f-5f5a6c98bd4c,Albania,Albanian National,Albanian,5,5. Number and Operations : Multiply a fraction...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
27,cb878111-2304-40d9-a5e2-d790b5975127,Albania,Albanian National,Albanian,5,6. Number and Operations : Divide unit fractio...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
28,ebab559c-d7cd-484c-89d3-de91dd104404,Albania,Albanian National,Albanian,5,7. Operations : Write and evaluate complex num...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
29,ea86cdcd-4323-4c98-bdd4-d4b310bd5d33,Albania,Albanian National,Albanian,5,"8. Operations : Read, write, compare, and roun...",1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
30,72042d7f-e19e-4672-bb14-0b542792e86c,Albania,Albanian National,Albanian,5,9. Operations : Perform addition and subtracti...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
31,f1b319cb-3794-4e4b-a03a-0634123f954a,Albania,Albanian National,Albanian,5,10. Measurement : Measure liquid volume using ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
32,ac2a3880-6d66-487c-8d7c-431488d83ed1,Albania,Albanian National,Albanian,5,11. Measurement : Convert measurements from a ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
33,d2710a07-03bc-4633-ba7d-91a403820728,Albania,Albanian National,Albanian,5,12. Measurement : Convert among different-size...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
34,30c7b16e-4e28-47b8-a9d7-bf8af1d8e6b0,Albania,Albanian National,Albanian,5,13. Geometry : Calculate perimeter as an attri...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
35,2b00a9d8-2ff4-4739-9602-eccf19355c14,Albania,Albanian National,Albanian,5,14. Geometry : Identify three-dimensional ge...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
36,cce35589-054f-4ea7-9acf-2580e98d673c,Albania,Albanian National,Albanian,5,15. Geometry : Find and identify the sides of ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
37,7fec96d7-c76e-4ea4-b553-18a64f4c8639,Albania,Albanian National,Albanian,5,16. Geometry : Recognize and name squares and ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
38,55bf414f-4234-4f7a-95a0-32964be3e2e0,Albania,Albanian National,Albanian,5,17. Geometry : Describe any given polygon by i...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
39,ae1804be-5bbd-4b99-9eb4-c3c49ea92413,Albania,Albanian National,Albanian,5,18. Geometry : Solve real-world problems to fi...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
40,68e93a64-c7cd-4be0-b2b7-cec52c274194,Albania,Albanian National,Albanian,5,19. Data handling : Solve real-world problems ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...
41,938617b9-3bb4-4b51-893d-f547983d5e73,Albania,Albanian National,Albanian,5,20. Data handling : Determine the numeric dif...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...

In [38]:
# Read the Excel file
examples_df = pd.read_excel(
    "data/albania.xlsx"
)

In [39]:
examples_df

,Curriculum,Grade,Topic,Learning objectives,Questions,Translated Questions,Answer,Translated answer
0,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,"Calculate the sum of two 2-digit numbers, corr...",Ana ka 27 mollë dhe blen edhe 16 të tjera në t...,Ana has 27 apples and buys 16 more at the mark...,43 mollë,43 apples
1,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Calculate the difference of two 2-digit number...,"Ina kishte 27 mollë. Ajo i dha shoqes së saj, ...",Ina had 27 apples. She gave 9 apples to her fr...,18 mollë,18 apples
2,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Multiply and add small numbers in practical co...,Arba ka 2 monedha me vlerë 50 lekë dhe 3 moned...,Arba has 2 coins worth 50 lek each and 3 coins...,160 lekë,160 lek
3,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Use division of whole numbers to solve problem...,Një librari shet libra për 2 lekë secilin. Nës...,A bookstore sells books for 2 lek each. If Arl...,4 libra,4 books
4,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Calculate a given percentage of a number and d...,Një klasë ka 40 nxënës dhe 10 prej tyre kanë ç...,If there are 40 students in a class and 10 of ...,25%,25%
5,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Operations,Translate word problems involving one or two a...,Një librari shiti gjithsej 48 libra gjatë një ...,A bookstore sold 48 books in one day. The numb...,16 libra,16 books
6,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Operations,"Solve practical word problems involving money,...",Një librari në Tiranë shet një libër për 85 le...,A bookstore in Tirana sells a notebook for 85 ...,60 lekë,60 lek
7,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Measurement,Measure the length of an object to the nearest...,Një autobus lokal përshkon një linjë 10 km të ...,A local bus travels a route that is 10 km long...,80 kilometers,80 kilometers
8,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Measurement,Measure the mass of an object using grams (g) ...,Një kompani në Dajt grumbullon 1 250 kg pleh. ...,A company in Dajt collects 95 kg of fertilizer...,53 kg,53 kg
9,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Data handeling,Solve one-step addition problems involving rea...,"Në një teatër kanë ardhur 23 fëmijë, dhe më vo...","At a theater, 23 children arrive, and later 17...",40 fëmijë,40 children
10,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,"Calculate the sum of two 3-digit numbers, corr...",Gjatë një aktiviteti për mbledhjen e fondeve n...,"During a school fundraiser, 416 trees were col...",795 pemë,795 trees
11,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,Solve practical addition and subtraction word ...,Një autobus ka 52 vende. Në stacionin e parë h...,"A bus has 52 seats. At the first stop, 36 pass...",22 vende bosh,22 empty seats
12,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,Multiply a whole number of up to four digits b...,Çmimi i një bilete për muzeun e Beratit është ...,The price of a museum ticket in Berat is 200 l...,700 lekë,700 lek
13,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,Perform simple addition of fractions,Nje tepsi me byrek u nda në 10 feta. Arbri hën...,A burek is divided into 10 slices. Arber eats ...,0.5,0.5
14,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number Systems\t\t\t,Perform addition using decimal numbers to the ...,Një dyqan shiti 12.5 kilogram miell në ditën e...,A shop sold 12.5 kilograms of flour on the fir...,22.1 kilogramë,22.1 kilograms
15,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number Systems\t\t\t,Multiply a decimal number precise to two decim...,Një shishe me lëng portokalli ka 1.25 litra. N...,A bottle of orange juice contains 1.25 liters....,7.5 litra,7.5 liters
16,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number Systems\t\t\t,"Add simple fractions with unlike denominators,...",Arta hedh 1/2 litër ujë në një kovë dhe më pas...,Arta pours 1/2 liter of water into a bucket an...,3/4 litra,3/4 liter
17,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Measurement,Solve word problems that involve different un...,Një autobus udhëton 180 km me shpejtësi konsta...,A bus travels 180 km at a constant speed and s...,60 km,60 km
18,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Measurement,Tell time to the exact minute on an analog clo...,"Ora e murit tregon 9:00. Pas 4 orësh, cila orë...",The wall clock shows 9:00. What time will it b...,1pm,13:00:00
19,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Measurement,Solve measurement problems that involve simple...,Elona ka 7/10 litër lëng dhe pi 1/4 litër. Sa ...,Elona has 7/10 of a liter of juice and drinks ...,9/20 litra,9/20 liter
20,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Data handeling,Display a set of measurement data that include...,Beni blen 2 1/2 kg mish dhe përdor 3/4 kg për ...,Beni buys 2 1/2 kilograms of meat and uses 3/4...,1 3/4 kg,1 3/4 kg
21,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Data handeling,Perform addition with mixed units (kilograms a...,Gjyshi mblodhi 5 kilogramë e 200 gramë fiq nga...,Grandpa picked 5 kilograms and 200 grams of fi...,5200 g,5200 g
22,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Learn that an angle is measured in units calle...,Një shumëkëndësh ka 6 brinjë. Sa është shuma e...,A polygon has 6 sides. What is the sum of its ...,720°,720°
23,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Identify and count the sides of composite figu...,Një katror bashkohet me një trekëndësh duke nd...,A square is joined with a triangle by sharing ...,5 brinjë,5 sides
24,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Compare fractions with unlike denominators by ...,"Klajdi piu 1/3​ e një shisheje me ujë, kurse S...","Klajdi drank 1/3 of a bottle of water, while S...",Klajdi,Klajdi
25,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Solve word problems by subtracting two multi-d...,Mali i Korabit ka lartësinë 2764 metra. Mali i...,"Mount Korab is 2,764 meters high. Mount Dajti ...",1151 metra,1151 meters
26,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Find a fraction of a whole number to solve wor...,Një libër me poezi për fëmijë ka 90 faqe. Poez...,A children's poetry book has 90 pages. Poems w...,9 faqe,9 pages
27,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Divide unit fractions by whole numbers and who...,Një tortë u pre në copa me madhësi 1/3. Sa per...,A cake is cut into 1/3-sized pieces. How many ...,3 persona,3 people
28,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Operations,Perform addition and subtraction of whole numb...,Në një tren ishin 267 pasagjerë. Në ndalesën e...,There were 267 passengers on a train. At the f...,245 pasagjerë,245 passengers
29,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Operations,"Read, write, compare, and round decimals to th...","Në pazar, një shalqi nga Divjaka peshonte 5.7 ...","At the market, one watermelon from Divjaka wei...",Shalqini nga Divjaka,Watermelon from Divjaka
30,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Operations,Perform addition and subtraction with decimals...,Genti bleu një libër 250.5 lekë dhe një ditar ...,Genti bought a book for 250.5 lek and a notebo...,99 lekë,99 lek
31,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Measurement,Measure liquid volume using milliliters (ml) a...,Një shishe me vaj ulliri mban 750 mililitra. S...,A bottle of olive oil holds 750 milliliters. H...,1500 ml,1500 ml
32,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Measurement,Convert measurements from a larger unit to a s...,Babai po mat dhomën e ndenjes. Ajo është 5 met...,A father measures the living room. It is 5 met...,530 cm,530 cm
33,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Measurement,Convert among different-sized standard measure...,Rrobaqepësja përdori 1 metër e 80 cm copë për ...,A tailor used 1 meter and 80 centimeters of fa...,180 cm,180 cm
34,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Calculate perimeter as an attribute of two-dim...,Brinja e një parcele me formë katrore është 12...,The side of a square shaped plot is 12m. Calcu...,48 metra,48 meters
35,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Identify three-dimensional geometric shapes,Një kapelë ditëlindjeje ka formën e një koni. ...,A birthday hat has the shape of a cone. How ma...,1 kulm,1 vertex
36,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Find and identify the sides of a three-dimensi...,Një bateri si ato që përdorim për telekomandën...,"A battery, like those used in remote controls,...",3 faqe,3 faces
37,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,"Recognize and name squares and triangles, pent...",Ardi ka një kuti kubike ku mban lodrat e tij. ...,Ardi has a cubic box where he keeps his toys. ...,6 faqe,6 faces
38,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Describe any given polygon by its key attribut...,Një trekëndësh barabrinjës ka perimetrin 36 cm...,An equilateral triangle has a perimeter of 36 ...,12 cm,12 cm
39,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Solve real-world problems to find the sides of...,Fleta e punës së Artës është katrore dhe perim...,"Arta’s worksheet is square, and its perimeter ...",21 cm,21 cm
40,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Data handeling,Solve real-world problems that require knowled...,Një dyqan shet 2.75 kg mollë dhe 3.6 kg portok...,A shop sold 2.75 kilograms of apples and 3.6 k...,6.35 kg,6.35 kg
41,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Data handeling,Determine the numeric difference between two ...,Pesha e Elirës është 35.4 kg. Motra e saj e vo...,Elira weighs 35.4 kg. Her younger sister weigh...,20.2 kg,20.2 kg

In [40]:

# --------------------------------------------------
# Create numeric grade column
# "Grade 3" -> 3
# "Grade 4" -> 4
# --------------------------------------------------
examples_df["grade"] = (
    examples_df["Grade"]
    .str.extract(r"(\d+)")
    .astype(int)
)

# --------------------------------------------------
# Create topic numbering that resets within each grade
# --------------------------------------------------
examples_df["topic_num"] = (
    examples_df.groupby("grade")
    .cumcount()
    .add(1)
)

# --------------------------------------------------
# Create topic column
# Format:
# 1. Topic : Learning Objectives
# 2. Topic : Learning Objectives
# ...
# --------------------------------------------------
examples_df["topic"] = (
    examples_df["topic_num"].astype(str)
    + ". "
    + examples_df["Topic"].astype(str).str.strip()
    + " : "
    + examples_df["Learning objectives"].astype(str).str.strip()
)

# Optional cleanup
examples_df = examples_df.drop(columns=["topic_num"])

In [41]:
examples_df

,Curriculum,Grade,Topic,Learning objectives,Questions,Translated Questions,Answer,Translated answer,grade,topic
0,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,"Calculate the sum of two 2-digit numbers, corr...",Ana ka 27 mollë dhe blen edhe 16 të tjera në t...,Ana has 27 apples and buys 16 more at the mark...,43 mollë,43 apples,3,1. Number and Operations : Calculate the sum o...
1,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Calculate the difference of two 2-digit number...,"Ina kishte 27 mollë. Ajo i dha shoqes së saj, ...",Ina had 27 apples. She gave 9 apples to her fr...,18 mollë,18 apples,3,2. Number and Operations : Calculate the diffe...
2,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Multiply and add small numbers in practical co...,Arba ka 2 monedha me vlerë 50 lekë dhe 3 moned...,Arba has 2 coins worth 50 lek each and 3 coins...,160 lekë,160 lek,3,3. Number and Operations : Multiply and add sm...
3,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Use division of whole numbers to solve problem...,Një librari shet libra për 2 lekë secilin. Nës...,A bookstore sells books for 2 lek each. If Arl...,4 libra,4 books,3,4. Number and Operations : Use division of who...
4,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Number and Operations,Calculate a given percentage of a number and d...,Një klasë ka 40 nxënës dhe 10 prej tyre kanë ç...,If there are 40 students in a class and 10 of ...,25%,25%,3,5. Number and Operations : Calculate a given p...
5,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Operations,Translate word problems involving one or two a...,Një librari shiti gjithsej 48 libra gjatë një ...,A bookstore sold 48 books in one day. The numb...,16 libra,16 books,3,6. Operations : Translate word problems involv...
6,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Operations,"Solve practical word problems involving money,...",Një librari në Tiranë shet një libër për 85 le...,A bookstore in Tirana sells a notebook for 85 ...,60 lekë,60 lek,3,7. Operations : Solve practical word problems ...
7,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Measurement,Measure the length of an object to the nearest...,Një autobus lokal përshkon një linjë 10 km të ...,A local bus travels a route that is 10 km long...,80 kilometers,80 kilometers,3,8. Measurement : Measure the length of an obje...
8,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Measurement,Measure the mass of an object using grams (g) ...,Një kompani në Dajt grumbullon 1 250 kg pleh. ...,A company in Dajt collects 95 kg of fertilizer...,53 kg,53 kg,3,9. Measurement : Measure the mass of an object...
9,ANC ( Albanian National Curriculum (Kurrikula ...,Class 3,Data handeling,Solve one-step addition problems involving rea...,"Në një teatër kanë ardhur 23 fëmijë, dhe më vo...","At a theater, 23 children arrive, and later 17...",40 fëmijë,40 children,3,10. Data handeling : Solve one-step addition p...
10,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,"Calculate the sum of two 3-digit numbers, corr...",Gjatë një aktiviteti për mbledhjen e fondeve n...,"During a school fundraiser, 416 trees were col...",795 pemë,795 trees,4,1. Number and Operations : Calculate the sum o...
11,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,Solve practical addition and subtraction word ...,Një autobus ka 52 vende. Në stacionin e parë h...,"A bus has 52 seats. At the first stop, 36 pass...",22 vende bosh,22 empty seats,4,2. Number and Operations : Solve practical add...
12,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,Multiply a whole number of up to four digits b...,Çmimi i një bilete për muzeun e Beratit është ...,The price of a museum ticket in Berat is 200 l...,700 lekë,700 lek,4,3. Number and Operations : Multiply a whole nu...
13,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number and Operations,Perform simple addition of fractions,Nje tepsi me byrek u nda në 10 feta. Arbri hën...,A burek is divided into 10 slices. Arber eats ...,0.5,0.5,4,4. Number and Operations : Perform simple addi...
14,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number Systems\t\t\t,Perform addition using decimal numbers to the ...,Një dyqan shiti 12.5 kilogram miell në ditën e...,A shop sold 12.5 kilograms of flour on the fir...,22.1 kilogramë,22.1 kilograms,4,5. Number Systems : Perform addition using dec...
15,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number Systems\t\t\t,Multiply a decimal number precise to two decim...,Një shishe me lëng portokalli ka 1.25 litra. N...,A bottle of orange juice contains 1.25 liters....,7.5 litra,7.5 liters,4,6. Number Systems : Multiply a decimal number ...
16,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Number Systems\t\t\t,"Add simple fractions with unlike denominators,...",Arta hedh 1/2 litër ujë në një kovë dhe më pas...,Arta pours 1/2 liter of water into a bucket an...,3/4 litra,3/4 liter,4,7. Number Systems : Add simple fractions with ...
17,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Measurement,Solve word problems that involve different un...,Një autobus udhëton 180 km me shpejtësi konsta...,A bus travels 180 km at a constant speed and s...,60 km,60 km,4,8. Measurement : Solve word problems that invo...
18,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Measurement,Tell time to the exact minute on an analog clo...,"Ora e murit tregon 9:00. Pas 4 orësh, cila orë...",The wall clock shows 9:00. What time will it b...,1pm,13:00:00,4,9. Measurement : Tell time to the exact minute...
19,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Measurement,Solve measurement problems that involve simple...,Elona ka 7/10 litër lëng dhe pi 1/4 litër. Sa ...,Elona has 7/10 of a liter of juice and drinks ...,9/20 litra,9/20 liter,4,10. Measurement : Solve measurement problems t...
20,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Data handeling,Display a set of measurement data that include...,Beni blen 2 1/2 kg mish dhe përdor 3/4 kg për ...,Beni buys 2 1/2 kilograms of meat and uses 3/4...,1 3/4 kg,1 3/4 kg,4,11. Data handeling : Display a set of measurem...
21,ANC ( Albanian National Curriculum (Kurrikula ...,Class 4,Data handeling,Perform addition with mixed units (kilograms a...,Gjyshi mblodhi 5 kilogramë e 200 gramë fiq nga...,Grandpa picked 5 kilograms and 200 grams of fi...,5200 g,5200 g,4,12. Data handeling : Perform addition with mix...
22,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Learn that an angle is measured in units calle...,Një shumëkëndësh ka 6 brinjë. Sa është shuma e...,A polygon has 6 sides. What is the sum of its ...,720°,720°,5,1. Geometry : Learn that an angle is measured ...
23,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Identify and count the sides of composite figu...,Një katror bashkohet me një trekëndësh duke nd...,A square is joined with a triangle by sharing ...,5 brinjë,5 sides,5,2. Geometry : Identify and count the sides of ...
24,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Compare fractions with unlike denominators by ...,"Klajdi piu 1/3​ e një shisheje me ujë, kurse S...","Klajdi drank 1/3 of a bottle of water, while S...",Klajdi,Klajdi,5,3. Number and Operations : Compare fractions w...
25,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Solve word problems by subtracting two multi-d...,Mali i Korabit ka lartësinë 2764 metra. Mali i...,"Mount Korab is 2,764 meters high. Mount Dajti ...",1151 metra,1151 meters,5,4. Number and Operations : Solve word problems...
26,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Find a fraction of a whole number to solve wor...,Një libër me poezi për fëmijë ka 90 faqe. Poez...,A children's poetry book has 90 pages. Poems w...,9 faqe,9 pages,5,5. Number and Operations : Find a fraction of ...
27,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Number and Operations,Divide unit fractions by whole numbers and who...,Një tortë u pre në copa me madhësi 1/3. Sa per...,A cake is cut into 1/3-sized pieces. How many ...,3 persona,3 people,5,6. Number and Operations : Divide unit fractio...
28,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Operations,Perform addition and subtraction of whole numb...,Në një tren ishin 267 pasagjerë. Në ndalesën e...,There were 267 passengers on a train. At the f...,245 pasagjerë,245 passengers,5,7. Operations : Perform addition and subtracti...
29,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Operations,"Read, write, compare, and round decimals to th...","Në pazar, një shalqi nga Divjaka peshonte 5.7 ...","At the market, one watermelon from Divjaka wei...",Shalqini nga Divjaka,Watermelon from Divjaka,5,"8. Operations : Read, write, compare, and roun..."
30,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Operations,Perform addition and subtraction with decimals...,Genti bleu një libër 250.5 lekë dhe një ditar ...,Genti bought a book for 250.5 lek and a notebo...,99 lekë,99 lek,5,9. Operations : Perform addition and subtracti...
31,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Measurement,Measure liquid volume using milliliters (ml) a...,Një shishe me vaj ulliri mban 750 mililitra. S...,A bottle of olive oil holds 750 milliliters. H...,1500 ml,1500 ml,5,10. Measurement : Measure liquid volume using ...
32,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Measurement,Convert measurements from a larger unit to a s...,Babai po mat dhomën e ndenjes. Ajo është 5 met...,A father measures the living room. It is 5 met...,530 cm,530 cm,5,11. Measurement : Convert measurements from a ...
33,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Measurement,Convert among different-sized standard measure...,Rrobaqepësja përdori 1 metër e 80 cm copë për ...,A tailor used 1 meter and 80 centimeters of fa...,180 cm,180 cm,5,12. Measurement : Convert among different-size...
34,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Calculate perimeter as an attribute of two-dim...,Brinja e një parcele me formë katrore është 12...,The side of a square shaped plot is 12m. Calcu...,48 metra,48 meters,5,13. Geometry : Calculate perimeter as an attri...
35,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Identify three-dimensional geometric shapes,Një kapelë ditëlindjeje ka formën e një koni. ...,A birthday hat has the shape of a cone. How ma...,1 kulm,1 vertex,5,14. Geometry : Identify three-dimensional geom...
36,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Find and identify the sides of a three-dimensi...,Një bateri si ato që përdorim për telekomandën...,"A battery, like those used in remote controls,...",3 faqe,3 faces,5,15. Geometry : Find and identify the sides of ...
37,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,"Recognize and name squares and triangles, pent...",Ardi ka një kuti kubike ku mban lodrat e tij. ...,Ardi has a cubic box where he keeps his toys. ...,6 faqe,6 faces,5,16. Geometry : Recognize and name squares and ...
38,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Describe any given polygon by its key attribut...,Një trekëndësh barabrinjës ka perimetrin 36 cm...,An equilateral triangle has a perimeter of 36 ...,12 cm,12 cm,5,17. Geometry : Describe any given polygon by i...
39,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Geometry,Solve real-world problems to find the sides of...,Fleta e punës së Artës është katrore dhe perim...,"Arta’s worksheet is square, and its perimeter ...",21 cm,21 cm,5,18. Geometry : Solve real-world problems to fi...
40,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Data handeling,Solve real-world problems that require knowled...,Një dyqan shet 2.75 kg mollë dhe 3.6 kg portok...,A shop sold 2.75 kilograms of apples and 3.6 k...,6.35 kg,6.35 kg,5,19. Data handeling : Solve real-world problems...
41,ANC ( Albanian National Curriculum (Kurrikula ...,Class 5,Data handeling,Determine the numeric difference between two ...,Pesha e Elirës është 35.4 kg. Motra e saj e vo...,Elira weighs 35.4 kg. Her younger sister weigh...,20.2 kg,20.2 kg,5,20. Data handeling : Determine the numeric di...

In [48]:
examples_df.iloc[2]["topic"]

'3. Number and Operations : Multiply and add small numbers in practical contexts (money), applying multiplication and addition operations'

In [50]:
albanian_df.iloc[2]["topic"]

'3. Number and Operations : Multiply a 1-digit number by a 1-digit number using the standard \xa0multiplication .'

In [42]:


# Keep only the columns needed for matching and examples
examples_df = examples_df[["grade", "topic", "Questions", "Answer"]]

# Merge on grade and topic
albanian_df = albanian_df.merge(
    examples_df,
    on=["grade", "topic"],
    how="left"
)

In [43]:
albanian_df

,UUID,country,curriculum,addressing,grade,topic,topic_list,zeroshot_prompt,language,multilingual_prompt,Questions,Answer
0,c63d5de6-0ef9-484a-b31d-19b5254b735d,Albania,Albanian National,Albanian,3,1. Number and Operations : Calculate the sum o...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Ana ka 27 mollë dhe blen edhe 16 të tjera në t...,43 mollë
1,25ec454c-a879-4ce1-9716-bedd0a4b55f3,Albania,Albanian National,Albanian,3,2. Number and Operations : Calculate the diff...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
2,c80031d5-0f9a-405f-8086-a46e01f545b3,Albania,Albanian National,Albanian,3,3. Number and Operations : Multiply a 1-digit ...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
3,3551bbd5-6360-4daa-ac8d-c9d3726f85d8,Albania,Albanian National,Albanian,3,4. Number and Operations : Divide a 1-digit nu...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
4,89cc30d5-bf9d-44cb-84ab-8bab34ee017d,Albania,Albanian National,Albanian,3,5. Number and Operations : Calculate a given ...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
5,0308671e-a310-4df0-979c-3bc7a312516a,Albania,Albanian National,Albanian,3,6. Operations : Translate word problems involv...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Një librari shiti gjithsej 48 libra gjatë një ...,16 libra
6,e525b2b2-3328-4f96-a75f-017217c6bb43,Albania,Albanian National,Albanian,3,7. Operations : Solve practical word problems ...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Një librari në Tiranë shet një libër për 85 le...,60 lekë
7,d1085428-d3e4-49b1-b2f4-cabe2eaadb69,Albania,Albanian National,Albanian,3,8. Measurement : Measure the length of an obje...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Një autobus lokal përshkon një linjë 10 km të ...,80 kilometers
8,3d05bfd3-778c-4ca4-a816-c5caf86658f7,Albania,Albanian National,Albanian,3,9. Measurement : Measure the mass of an object...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
9,226a4aa9-8b0c-4ad5-876c-2549a6ed4a80,Albania,Albanian National,Albanian,3,"10. Data handling : Solve one-step ""how many m...",1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
10,ef740079-d428-4c1e-92b7-95b9a369840f,Albania,Albanian National,Albanian,4,1. Number and Operations : Calculate the sum o...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Gjatë një aktiviteti për mbledhjen e fondeve n...,795 pemë
11,1db53124-22bb-4f6d-9ac8-39286dcdc990,Albania,Albanian National,Albanian,4,2. Number and Operations : Calculate the diff...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
12,5ee2540a-3693-477a-a0a2-e26a884b9b53,Albania,Albanian National,Albanian,4,3. Number and Operations : Multiply a whole nu...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
13,98b54745-4448-4451-8501-9f76d8c3322d,Albania,Albanian National,Albanian,4,4. Number and Operations : Divide whole number...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
14,4311be70-5fb3-4b72-8f80-f4d3ea5d55a3,Albania,Albanian National,Albanian,4,5. Number Systems : Perform addition using dec...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
15,ce16dc70-b357-4f0b-8317-9feb26bfd4c4,Albania,Albanian National,Albanian,4,6. Number Systems : Perform subtract using dec...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
16,2d176d9b-d9d4-42da-9bbc-12400933be6f,Albania,Albanian National,Albanian,4,7. Number Systems : Locate and plot positive a...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
17,000f181e-3b39-439c-a9a8-994313a60c75,Albania,Albanian National,Albanian,4,8. Measurement : Solve word problems that inv...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
18,d2d1313a-98a7-4824-8979-452f0d2ee0e5,Albania,Albanian National,Albanian,4,9. Measurement : Tell time to the exact minute...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,"Ora e murit tregon 9:00. Pas 4 orësh, cila orë...",1pm
19,1e86b171-eb0a-4485-abed-6cb3a6f70708,Albania,Albanian National,Albanian,4,10. Measurement : Solve measurement problems t...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Elona ka 7/10 litër lëng dhe pi 1/4 litër. Sa ...,9/20 litra
20,bc514ad7-497b-4c30-b9ab-a02154762e49,Albania,Albanian National,Albanian,4,11. Data handling : Display a set of measureme...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
21,84f47e2a-1023-4e5c-8301-3e305ff46290,Albania,Albanian National,Albanian,4,12. Data handling : Answer questions about th...,1. Number and Operations : Calculate the sum o...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
22,4aad8cf7-3696-40e1-8728-1c0146a5e78d,Albania,Albanian National,Albanian,5,1. Geometry : Learn that an angle is measured ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Një shumëkëndësh ka 6 brinjë. Sa është shuma e...,720°
23,9a91392a-3849-4d35-97de-ed50ccb8785d,Albania,Albanian National,Albanian,5,2. Geometry : Sort triangles into groups based...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
24,f6cf06f0-50f4-44da-b264-33621c71fa4b,Albania,Albanian National,Albanian,5,3. Number and Operations : Add and subtract fr...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
25,f7f09787-20aa-4d2b-be7f-30e5f7999c58,Albania,Albanian National,Albanian,5,4. Number and Operations : Compare any two who...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
26,b5ad2eff-6704-4c25-b92f-5f5a6c98bd4c,Albania,Albanian National,Albanian,5,5. Number and Operations : Multiply a fraction...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
27,cb878111-2304-40d9-a5e2-d790b5975127,Albania,Albanian National,Albanian,5,6. Number and Operations : Divide unit fractio...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Një tortë u pre në copa me madhësi 1/3. Sa per...,3 persona
28,ebab559c-d7cd-484c-89d3-de91dd104404,Albania,Albanian National,Albanian,5,7. Operations : Write and evaluate complex num...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
29,ea86cdcd-4323-4c98-bdd4-d4b310bd5d33,Albania,Albanian National,Albanian,5,"8. Operations : Read, write, compare, and roun...",1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
30,72042d7f-e19e-4672-bb14-0b542792e86c,Albania,Albanian National,Albanian,5,9. Operations : Perform addition and subtracti...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
31,f1b319cb-3794-4e4b-a03a-0634123f954a,Albania,Albanian National,Albanian,5,10. Measurement : Measure liquid volume using ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
32,ac2a3880-6d66-487c-8d7c-431488d83ed1,Albania,Albanian National,Albanian,5,11. Measurement : Convert measurements from a ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Babai po mat dhomën e ndenjes. Ajo është 5 met...,530 cm
33,d2710a07-03bc-4633-ba7d-91a403820728,Albania,Albanian National,Albanian,5,12. Measurement : Convert among different-size...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
34,30c7b16e-4e28-47b8-a9d7-bf8af1d8e6b0,Albania,Albanian National,Albanian,5,13. Geometry : Calculate perimeter as an attri...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Brinja e një parcele me formë katrore është 12...,48 metra
35,2b00a9d8-2ff4-4739-9602-eccf19355c14,Albania,Albanian National,Albanian,5,14. Geometry : Identify three-dimensional ge...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
36,cce35589-054f-4ea7-9acf-2580e98d673c,Albania,Albanian National,Albanian,5,15. Geometry : Find and identify the sides of ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Një bateri si ato që përdorim për telekomandën...,3 faqe
37,7fec96d7-c76e-4ea4-b553-18a64f4c8639,Albania,Albanian National,Albanian,5,16. Geometry : Recognize and name squares and ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
38,55bf414f-4234-4f7a-95a0-32964be3e2e0,Albania,Albanian National,Albanian,5,17. Geometry : Describe any given polygon by i...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,Një trekëndësh barabrinjës ka perimetrin 36 cm...,12 cm
39,ae1804be-5bbd-4b99-9eb4-c3c49ea92413,Albania,Albanian National,Albanian,5,18. Geometry : Solve real-world problems to fi...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
40,68e93a64-c7cd-4be0-b2b7-cec52c274194,Albania,Albanian National,Albanian,5,19. Data handling : Solve real-world problems ...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN
41,938617b9-3bb4-4b51-893d-f547983d5e73,Albania,Albanian National,Albanian,5,20. Data handling : Determine the numeric dif...,1. Geometry : Learn that an angle is measured ...,Your task is to create exactly one math word p...,Albanian,Your task is to create exactly one math word p...,NaN,NaN

In [52]:

# Create example_1 column
albanian_df["example_1"] = albanian_df.apply(
    lambda row: json.dumps(
        {
            "question": row["Questions"],
            "answer": row["Answer"]
        },
        ensure_ascii=False
    ) if pd.notna(row["Questions"]) and pd.notna(row["Answer"]) else None,
    axis=1
)

# Optional: remove the temporary columns
albanian_df = albanian_df.drop(columns=["Questions", "Answer"])

In [12]:
examples = pd.read_excel(
    "data/india.xlsx",
    sheet_name="Correct_3ver_Final_Updated"
)

examples = examples.rename(columns={"Grade": "grade"})

examples = examples.reset_index(drop=True)

In [13]:


# Create one row per unique grade-topic-learning objective
unique_topics = (
    examples[["grade", "Topic", "Learning Objective"]]
    .drop_duplicates()
    .copy()
)

# Number unique topics within each grade
unique_topics["topic_num"] = (
    unique_topics.groupby("grade")
    .cumcount()
    .add(1)
)

# Merge topic numbers back to all example rows
examples = examples.merge(
    unique_topics,
    on=["grade", "Topic", "Learning Objective"],
    how="left"
)

# Create topic column
examples["topic"] = (
    examples["topic_num"].astype(str)
    + ". "
    + examples["Topic"].astype(str).str.strip()
    + " : "
    + examples["Learning Objective"].astype(str).str.strip()
)

examples = examples.drop(columns=["topic_num"])

In [7]:


# Make sure matching columns have same names/types
examples["grade"] = examples["grade"].astype(int)
hindi_df["grade"] = hindi_df["grade"].astype(int)

examples["topic"] = examples["topic"].astype(str).str.strip()
hindi_df["topic"] = hindi_df["topic"].astype(str).str.strip()

# Create JSON string for each example row
examples["example_json"] = examples.apply(
    lambda row: json.dumps(
        {
            "question": row["Hindi question"],
            "answer": row["Answer_Hindi"]
        },
        ensure_ascii=False
    ),
    axis=1
)



# Number examples within each grade-topic pair
examples["example_num"] = (
    examples.groupby(["grade", "topic"])
    .cumcount()
    .add(1)
)

# Keep only the first 10 examples for each grade-topic pair
examples = examples[examples["example_num"] <= 10].copy()

# Convert example_num to column names
examples["example_col"] = "example_" + examples["example_num"].astype(str)

# Pivot into wide format
examples_wide = examples.pivot_table(
    index=["grade", "topic"],
    columns="example_col",
    values="example_json",
    aggfunc="first"
).reset_index()

examples_wide.columns.name = None

In [ ]:
# Merge into hindi_df
hindi_df = hindi_df.merge(
    examples_wide,
    on=["grade", "topic"],
    how="left"
)

In [10]:
hindi_df.to_excel(
    "data/hindi.xlsx",
    index=False
)

In [14]:
examples = pd.read_excel(
    "data/india.xlsx",
    sheet_name="Correct_3ver_Final_Updated"
)

examples = examples.rename(columns={"Grade": "grade"})

examples = examples.reset_index(drop=True)

In [15]:


# Create one row per unique grade-topic-learning objective
unique_topics = (
    examples[["grade", "Topic", "Learning Objective"]]
    .drop_duplicates()
    .copy()
)

# Number unique topics within each grade
unique_topics["topic_num"] = (
    unique_topics.groupby("grade")
    .cumcount()
    .add(1)
)

# Merge topic numbers back to all example rows
examples = examples.merge(
    unique_topics,
    on=["grade", "Topic", "Learning Objective"],
    how="left"
)

# Create topic column
examples["topic"] = (
    examples["topic_num"].astype(str)
    + ". "
    + examples["Topic"].astype(str).str.strip()
    + " : "
    + examples["Learning Objective"].astype(str).str.strip()
)

examples = examples.drop(columns=["topic_num"])

In [16]:


# Make sure matching columns have same names/types
examples["grade"] = examples["grade"].astype(int)
marathi_df["grade"] = marathi_df["grade"].astype(int)

examples["topic"] = examples["topic"].astype(str).str.strip()
marathi_df["topic"] = marathi_df["topic"].astype(str).str.strip()

# Create JSON string for each example row
examples["example_json"] = examples.apply(
    lambda row: json.dumps(
        {
            "question": row["Marathi Question"],
            "answer": row["Answer Marathi"]
        },
        ensure_ascii=False
    ),
    axis=1
)



# Number examples within each grade-topic pair
examples["example_num"] = (
    examples.groupby(["grade", "topic"])
    .cumcount()
    .add(1)
)

# Keep only the first 10 examples for each grade-topic pair
examples = examples[examples["example_num"] <= 10].copy()

# Convert example_num to column names
examples["example_col"] = "example_" + examples["example_num"].astype(str)

# Pivot into wide format
examples_wide = examples.pivot_table(
    index=["grade", "topic"],
    columns="example_col",
    values="example_json",
    aggfunc="first"
).reset_index()

examples_wide.columns.name = None

In [17]:
marathi_df = marathi_df.merge(
    examples_wide,
    on=["grade", "topic"],
    how="left"
)

In [18]:
marathi_df

,UUID,country,curriculum,addressing,grade,topic,topic_list,zeroshot_prompt,language,multilingual_prompt,example_1,example_10,example_2,example_3,example_4,example_5,example_6,example_7,example_8,example_9
0,a07f2813-d483-4758-9226-b16806a5252c,India,NCERT,Indian,3,1. Counting : reads and writes numbers up to 9...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""गौरवचा रोल नंबर 150 आहे. गौरवच्य...","{""question"": ""572 या संख्येत, शतकांच्या ठिकाणी...","{""question"": ""572 या संख्येत, शतकांच्या ठिकाणी...","{""question"": ""राहुलचा रोल नंबर 299 नंतर आहे.\n...","{""question"": ""719 या संख्येत, दहाव्या ठिकाणी क...","{""question"": ""मी 3 अंकी संख्या आहे. माझे शतकां...","{""question"": ""692 या संख्येत, शंभर ठिकाणी कोणत...","{""question"": ""4, 9 आणि 0 या अंकांचा वापर करून ...","{""question"": ""864 या संख्येत, दहाव्या ठिकाणी क...","{""question"": ""स्नेहाचा रोल नंबर 26 आहे. स्नेहा..."
1,1b379528-1f4b-428b-a789-2c77ce9c11f7,India,NCERT,Indian,3,2. Compare numbers : compares numbers up to 99...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""सर्वात लहान संख्या लिहा: 562, 62...","{""question"": ""एका क्रिकेट सामन्यात भारताने 447...","{""question"": ""सर्वात मोठी संख्या लिहा: 709, 97...","{""question"": ""912, 921 आणि 129 पैकी सर्वात मोठ...","{""question"": ""या गटातील सर्वात लहान संख्या लिह...","{""question"": ""सर्वात लहान ते सर्वात मोठ्या संख...","{""question"": ""सर्वात मोठ्या ते सर्वात लहान संख...","{""question"": ""रियाकडे ₹ 324 आहेत आणि तिच्या भा...","{""question"": ""दिल्लीतील एका दुकानाने सोमवारी 4...","{""question"": ""एका बसने सकाळी 375 आणि संध्याकाळ..."
2,b7fd0f99-cd4d-4a06-97a3-012e42f2e44f,India,NCERT,Indian,3,3. addition : solves simple daily life problem...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""एका ग्रंथालयात 124 कथापुस्तके आण...","{""question"": ""एका शेतकऱ्याने पहिल्या आठवड्यात ...","{""question"": ""रवीने गेल्या वर्षी 78 आणि या वर्...","{""question"": ""एका शाळेतील कार्यक्रमात 135 मुले...","{""question"": ""एका फळ विक्रेत्याने सकाळी 67 आणि...","{""question"": ""एका बसमध्ये सकाळी 42 आणि दुपारी ...","{""question"": ""एका शेतकऱ्याने एका शेतातून 93 कि...","{""question"": ""एका क्रिकेट सामन्यात, टीम अ ने प...","{""question"": ""रीनाने सकाळी समुद्रकिनाऱ्यावर 48...","{""question"": ""प्रियाने सोमवारी 186 पाने आणि मं..."
3,45a7bc7a-e98d-4c95-ad0f-22f61f42be4c,India,NCERT,Indian,3,4. subtraction : solves simple daily life prob...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""एका फळ विक्रेत्याकडे 120 सफरचंद ...","{""question"": ""एका शाळेत 180 विद्यार्थी होते. 6...","{""question"": ""प्रियाकडे 92 गोळ्या होत्या. तिने...","{""question"": ""एका ग्रंथालयात 250 पुस्तके होती....","{""question"": ""अर्जुनने 134 तिकिटे गोळा केले. त...","{""question"": ""रोहनकडे ₹275 होते. त्याने ₹138 ल...","{""question"": ""एका फळ विक्रेत्याकडे सकाळी 342 स...","{""question"": ""एका शाळेच्या ग्रंथालयात 450 पुस्...","{""question"": ""सीतेकडे हार बनवण्यासाठी 325 मणी ...","{""question"": ""एका शेतकऱ्याकडे 500 किलो तांदूळ ..."
4,299ea439-4563-4280-86fa-b24070d4b7b3,India,NCERT,Indian,3,5. addition and subtraction : solves simple da...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""रवीने एका दुकानातून 78 आणि दुसऱ्...","{""question"": ""एका कंपनीने 480 टेबले बनवली. तिन...","{""question"": ""नेहाकडे 120 चॉकलेट होते. तिने ति...","{""question"": ""प्रियाने ₹120, ₹135, ₹150 आणि ₹1...","{""question"": ""एका फळ विक्रेत्याकडे 180 सफरचंद ...","{""question"": ""एका दुकानदाराकडे 300 पेन्सिल होत...","{""question"": ""राजकडे ₹250 होते. त्याने एका पुस...","{""question"": ""एका दुकानदाराकडे 400 किलो तांदूळ...","{""question"": ""एका शाळेत 320 विद्यार्थी होते. 8...","{""question"": ""मीनाकडे 180 पेन्सिल होत्या. तिने..."
5,20c201ba-537b-4303-a141-5ee1868af1c4,India,NCERT,Indian,3,6. multiplication : constructs and uses the mu...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""सीमाकडे 4 फोटो अल्बम आहेत. प्रत्...","{""question"": ""एका बेकरीमध्ये दररोज 14 बिस्किटा...","{""question"": ""अमितने ३ मेणरंगांचे पॅक विकत घेत...","{""question"": ""वर्गात खुर्च्यांच्या 6 रांगा आहे...","{""question"": ""प्रियाकडे 7 बरण्या आहेत. प्रत्ये...","{""question"": ""रवीने टोमॅटोच्या 5 ओळी लावल्या. ...","{""question"": ""एका बॉक्समध्ये 6 खेळण्यांच्या गा...","{""question"": ""अमनकडे 6 पेट्या आहेत. प्रत्येक प...","{""question"": ""एका शिक्षकाने वर्गात 8 ओळींच्या ...","{""question"": ""एका बागेत 12 फुलांच्या कुंड्या आ..."
6,44577776-1379-4609-9b1b-312d0b9b29c6,India,NCERT,Indian,3,7. division : explains the meaning of division...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""रवीकडे 24 आंबे आहेत. तो ते 6 मित...","{""question"": ""एका शिक्षिकेकडे 48 पेन्सिल आहेत....","{""question"": ""एका शिक्षिकेकडे 30 चॉकलेट आहेत. ...","{""question"": ""18 पेन्सिल आहेत ज्या 3 बॉक्समध्य...","{""question"": ""रोहनकडे 42 गोट्या आहेत. तो ते त्...","{""question"": ""एका फळ विक्रेत्याकडे 36 सफरचंद आ...","{""question"": ""मीनाकडे 20 बांगड्या आहेत. तिला त...","{""question"": ""प्रत्येक बॉक्समध्ये 4 लाडू असतील...","{""question"": ""एका काड्यात रसाच्या 30 बाटल्या अ...","{""question"": ""रवीकडे 40 गोळ्या आहेत. तो त्या..."
7,619349c5-3c19-4783-bc9c-37c85cc447a6,India,NCERT,Indian,3,8. fraction : represents the fractions as half...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""अमनकडे 10 सफरचंद आहेत. त्याने त्...","{""question"": ""रवीकडे 7 पतंग आहेत आणि सोहमकडे र...","{""question"": ""रियाकडे 14 पेन्सिल आहेत. त्यापैक...","{""question"": ""एका टोपलीत 20 आंबे आहेत. राजने त...","{""question"": ""मीनाकडे 18 गोळ्या होत्या. तिने ...","{""question"": ""एका बॉक्समध्ये 12 रंगीत रंग असता...","{""question"": ""सीमाने 16 बिस्किटे तयार केल्या. ...","{""question"": ""रोहनकडे 5 पेन्सिल आहेत आणि मोहनक...","{""question"": ""अमनकडे 4 चॉकलेट आहेत आणि राहुलकड...","{""question"": ""प्रियाकडे 6 कथापुस्तके आहेत आणि ..."
8,a4376674-2023-4f04-8e03-0d52352b1479,India,NCERT,Indian,3,9. measurement of length : estimates and measu...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""नेहाचे पुस्तक 4 हात लांब आहे. ति...",NaN,"{""question"": ""एका टेबलाची लांबी 8 हातपआहे. एका...","{""question"": ""एक साडी 20 हात लांब असते. एक दुप...","{""question"": ""दोरी मोजण्याच्या टेपपेक्षा लांब ...","{""question"": ""ट्रेन बसपेक्षा लांब असते. बस कार...","{""question"": ""एका कपाटाच्या कप्प्याची लांबी ६ ...","{""question"": ""विक्रम त्याच्या पावलांचा वापर कर...","{""question"": ""बैठकीच्या खोलीतील एक चटई 7 हात ल...",NaN
9,da948fe6-5eb9-4149-ac62-b707058435bc,India,NCERT,Indian,3,10. measurement of weight : weighs objects usi...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3e9bae4d-3c30-419a-b9d6-7fb610df2224,India,NCERT,Indian,3,11. measurement of capacity : compares the cap...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,c587ba86-9712-4b39-9664-ef609df9cdfd,India,NCERT,Indian,3,12. calendar : identifies a particular day and...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,d9e4893a-552c-4c6e-aa99-1758be6a9fe2,India,NCERT,Indian,3,13. time : reads the time correctly to the hou...,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""राहुलने संध्याकाळी 4:30 वाजता गृ...","{""question"": ""मीनाने सकाळी 10:20 वाजता रंगकाम ...","{""question"": ""एक फुटबॉल सामना दुपारी 3:20 वाजत...","{""question"": ""दुपारी 2:10 वाजता ओव्हनमध्ये एक ...","{""question"": ""शाळेची सभा सकाळी 8:00 वाजता सुरू...","{""question"": ""कुणालने संध्याकाळी 6:10 वाजता खे...","{""question"": ""अर्जुन सकाळी 7:45 वाजता शाळेसाठी...","{""question"": ""नेहाने दुपारी 3:15 वाजता खेळायला...","{""question"": ""रमेशने दुपारी 2:10 वाजता पुस्तक ...","{""question"": ""सीतेने संध्याकाळी 5:30 वाजता स्व..."
13,b05f2da1-c123-4fdb-bac7-8b9ecb7691f1,India,NCERT,Indian,3,14. Pattern : extends patterns in numbers,1. Counting : reads and writes numbers up to 9...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""रिया एका क्रमामध्ये आंबे मांडत आ...","{""question"": ""गहाळ संख्या भरा:\n90, 80, 70, __...","{""question"": ""दररोज योग करणाऱ्या विद्यार्थ्यां...","{""question"": ""एका क्रमात 9 चा तक्ता दाखवला आहे...","{""question"": ""एक ठिपका नमुना अशा प्रकारे वाढतो...","{""question"": ""रेल्वे कोच नंबर पॅटर्न असा असतो:...","{""question"": ""राणी लाडू एका पॅटर्नमध्ये लावते:...","{""question"": ""मोहन पूजेसाठी फुले लावत आहे:\nगु...","{""question"": ""प्रत्येक वेळी एक नमुना 5 ने कमी ...","{""question"": ""डोमिनो शैलीतील बिंदूंचा नमुना वा..."
14,1d027ad9-d1d0-4f7f-8413-dc7c755fab90,India,NCERT,Indian,4,1. addition : solves simple daily life problem...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""दिल्लीतील एका ग्रंथालयात 2,467 ह...",NaN,"{""question"": ""एका शेतकऱ्याने एका महिन्यात 4,13...","{""question"": ""एका शालेय मेळ्यात शनिवारी 7,294 ...","{""question"": ""एका पोस्ट ऑफिसने सकाळी 3,651 आणि...","{""question"": ""एका दुकानदाराने सकाळी ₹8,042 आणि...","{""question"": ""एका शहरातील दोन शाळांमध्ये अनुक्...","{""question"": ""एका ट्रेनने पहिल्या आठवड्यात 5,8...","{""question"": ""जानेवारीमध्ये एका रुग्णालयात 7,4...",NaN
15,db46d788-4552-4581-bccb-fde7aa08b21c,India,NCERT,Indian,4,2. subtraction : solves simple daily life prob...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""एका शाळेने 5,432 परीक्षेचे पेपर ...","{""question"": ""एका शेतकऱ्याकडे 6,700 किलो तांदू...","{""question"": ""तुम्हाला खालील संख्या जोड्या दिल...","{""question"": ""गेल्या वर्षी एका शाळेत 6,250 विद...","{""question"": ""एका दुकानदाराकडे ₹9,300 होते. त्...","{""question"": ""दिल्लीतील एका शाळेत 5,438 विद्या...","{""question"": ""नोएडा येथील एका खेळण्यांच्या कार...","{""question"": ""भारतीय रेल्वेमध्ये एका प्रदेशात ...","{""question"": ""पंजाबमधील एका शेतकऱ्याने यावर्षी...","{""question"": ""हरियाणातील एका गोदामातून तांदूळ ..."
16,1111dd6b-8575-4fa2-8cda-4286ea256a17,India,NCERT,Indian,4,3. multiplication : multiplies 2 and 3 digit n...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""एक फळ विक्रेता एका दिवसात 18 सफर...","{""question"": ""एका ट्रकमध्ये 175 पोती तांदूळ वा...","{""question"": ""एका शेतकऱ्याकडे 28 आंब्याची झाडे...","{""question"": ""एका शाळेत 125 बाक आहेत. प्रत्येक...","{""question"": ""एका शेतकऱ्याने 132 आंब्याची झाडे...","{""question"": ""एका पुस्तक प्रकाशकाने प्रत्येक ब...","{""question"": ""एक बांधकाम कामगार एका ओळीत 245 व...","{""question"": ""एका कापड गिरणीतून दररोज 326 मीटर...","{""question"": ""एका बसमध्ये 45 आसने आहेत. जर 12 ...","{""question"": ""एक भाजी विक्रेता एका दिवसात 34 क..."
17,f24b4a3f-02ae-499b-b4d8-a88710d3388d,India,NCERT,Indian,4,4. division : divides a number by another numb...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""एका शाळेत 864 विद्यार्थी आहेत. ज...","{""question"": ""एका शाळेत 240 विद्यार्थी आहेत आण...","{""question"": ""एका शेतकऱ्याकडे 432 सफरचंद आहेत....","{""question"": ""एका शाळेच्या सहलीला 438 मुले जात...","{""question"": ""एका घाऊक विक्रेत्याकडे 502 किलो ...","{""question"": ""एका कारखान्यात एका दिवसाला 252 ख...","{""question"": ""एका ट्रकमध्ये 432 किलो तांदूळ वा...","{""question"": ""एका कारखान्यात 4,50 बिस्किटे तया...","{""question"": ""रीताकडे ₹10 च्या नोटांमध्ये 200 ...","{""question"": ""एका पुस्तकांच्या दुकानाला 1,80 प..."
18,763fd579-3787-4917-8083-65f737868f85,India,NCERT,Indian,4,5. fraction : finds the number corresponding t...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""एका फळ विक्रेत्याकडे 90 सफरचंद आ...","{""question"": ""एका टोपलीत 60 आंबे आहेत. त्यापैक...","{""question"": ""एका केकचे 5 समान भाग केले आहेत. ...","{""question"": ""एका पाण्याच्या टाकीत 90 लिटर पाण...","{""question"": ""एका टोपलीत 45 आंबे आहेत. नेहाने ...","{""question"": ""एका बेकरीने 30 केक बेक केले. एका...","{""question"": ""एका वर्गात 60 जागा आहेत. त्यापैक...","{""question"": ""एका बॉक्समध्ये 40 चॉकलेट आहेत. र...","{""question"": ""आशाने रात्रीच्या जेवणासाठी 12 चप...","{""question"": ""एका कलिंगडाचे वजन 9 किलो असते. ज..."
19,67909c1d-5ac9-4c9f-97f4-85b584cdc125,India,NCERT,Indian,4,6. measurement : solves problem involving dail...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""10 मिली डोसिंग कपमध्ये किती 1 मि...","{""question"": ""वर्गातील ब्लॅकबोर्डची धार 300 से...","{""question"": ""250 मिली ग्लासमध्ये किती 10 मिली...","{""question"": ""एक कारखाना 500 मिली रसाच्या बाटल...","{""question"": ""500 ग्रॅम साखरेच्या एका पॅकेटचे ...","{""question"": ""10 किलोमध्ये 500 ग्रामचे किती पॅ...","{""question"": ""जर डाळीच्या एका पॅकेटचे वजन 250 ...","{""question"": ""जर एका रबरचे वजन 10 ग्रॅम असेल, ...","{""question"": ""जर एका रबरचे वजन 10 ग्रॅम असेल त...","{""question"": ""एका दुकानात प्रत्येक पॅकेटमध्ये ..."
20,3da95529-5122-477b-b5f6-e3b1b5fedd10,India,NCERT,Indian,4,7. measurement of length : converts metre into...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""एका कपाटाची लांबी 3 मीटर आहे. रा...","{""question"": ""एका काठीची लांबी 5 मीटर असते आणि...","{""question"": ""राम आणि शाम यांची उंची सारखीच आह...","{""question"": ""एका बोर्डची लांबी 2 मीटर आहे. सो...","{""question"": ""एक दोरी 5 मीटर लांब आहे. जर प्रत...","{""question"": ""एका दोरीची लांबी 20 मीटर आहे. एक...","{""question"": ""एका शिंप्याला एक पडदा बनवण्यासाठ...","{""question"": ""नेहा तिच्या वडिलांना लाकडी फळीची...","{""question"": ""एका रिबनची लांबी 95 सेंटीमीटर अस...","{""question"": ""एका कापडाची लांबी 345 सेंटीमीटर ..."
21,c81e514d-90c4-4dbb-b8c0-c9920563f90a,India,NCERT,Indian,4,8. time : calculates time intervals/ duration ...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""तास काटा 6 वाजता आहे. पुन्हा 6 व...",NaN,"{""question"": ""एक ट्रेन सकाळी 9:45 वाजता स्टेशन...","{""question"": ""सीमाने संध्याकाळी 6:00 वाजता चित...","{""question"": ""रियाने दिल्लीहून सकाळी 7:45 वाजत...","{""question"": ""स्नेहाची शाळा सकाळी 9:15 वाजता स...","{""question"": ""एक फुटबॉल सामना 4:45 वाजता सुरू ...","{""question"": ""रवी सकाळी 7:30 वाजता शाळेसाठी घर...","{""question"": ""अनिताने दुपारी 3:20 वाजता तिचे स...",NaN
22,677eee0d-506d-45df-ac4a-742c6024744d,India,NCERT,Indian,4,9. time : relates to 24 hr clock with respect ...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,da8e4803-1bef-4630-9769-bfd4b157d264,India,NCERT,Indian,4,10. time : reads clock time in hour and minute...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,b6be91d1-ac61-4800-8605-6e32ba07df9a,India,NCERT,Indian,4,11. data handling : represents the collected i...,1. addition : solves simple daily life problem...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0080fcac-17d3-4eae-b010-66fab1af8849,India,NCERT,Indian,5,1. fraction : identifies and forms equivalent ...,1. fraction : identifies and forms equivalent ...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""मीनाने एका रिबनचे 8 समान भाग केल...",NaN,"{""question"": ""5/10 च्या समतुल्य अपूर्णांक ओळखा...","{""question"": ""अर्जुनने सकाळी त्याच्या कथापुस्त...","{""question"": ""खालीलपैकी कोणत्या जोड्या समतुल्य...","{""question"": ""रियाने डोस्याच्या 2/4 भाग खाल्ले...","{""question"": ""सान्याने तिच्या कलाकृतीसाठी 4/8 ...","{""question"": ""एका ट्रेनने प्रवासाचा 8/16 भाग प...","{""question"": ""कोणता अपूर्णांक 4/16 च्या समतुल्...","{""question"": ""यापैकी कोणता अंक 9/12 च्या बरोबर..."
26,2729bbcb-33b8-407f-8b12-1815f69fa8be,India,NCERT,Indian,5,2. fraction : compares fractions,1. fraction : identifies and forms equivalent ...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""रवी आणि मोहनने एक प्लेट जिलेबी ख...",NaN,"{""question"": ""आशाने सुट्टीच्या वेळी तिची पाण्य...","{""question"": ""शाळेतील दुपारच्या जेवणाच्या वेळी...","{""question"": ""लाडू बनवण्याच्या स्पर्धेत, गट अ ...","{""question"": ""स्वच्छता मोहिमेत दोन वर्गांनी भा...","{""question"": ""खो-खो खेळत असताना, संघ अ ने मालि...","{""question"": ""एका कला वर्गात, वीरने मंडळाचा 3/...","{""question"": ""स्वच्छता मोहिमेत दोन वर्गांनी भा...",NaN
27,549b53e6-4f27-443e-b1a4-65bc7064ae0d,India,NCERT,Indian,5,3. fraction : solves problems on daily life si...,1. fraction : identifies and forms equivalent ...,Your task is to create exactly one math word p...,Marathi,Your task is to create exactly one math word p...,"{""question"": ""आयशाने सकाळी 1/3 लिटर आणि संध्या...",NaN,"{""question"": ""एका दुकानदाराने चॉकलेटचा एक बार ...","{""question"": ""मीनाकडे 2 मीटर लांबीचा रिबन आहे....","{""question"": ""एका बादलीत 20 लिटर पाणी साठू शकत...","{""question"": ""शनायाने शनिवारी तिच्या पुस्तकाचा...","{""question"": ""एका क्रिकेट सामन्यादरम्यान, विरा...","{""question"": ""रितिका तिच्या शिकवणीला जाण्यासाठ...","{""question"": ""रियाने बाटलीचा 7/10 भाग लिंबूपाण...",NaN

In [19]:
marathi_df.to_excel(
    "data/marathi.xlsx",
    index=False
)